### ISSUE TITLE
Local builds: `netlify build` followed by `netlify deploy` doesn't work with Next.js sites

### ISSUE THREAD

**Issue by rks118** [opennextjs/opennextjs-netlify#2501]
Local build (`netlify build`) will output `_next` in `.next`, but disappear immediately.

As a result, the website could not find js/css/image resources after I deployed(`netlify deploy --prod`) it.

Screen Record:

[https://github.com/netlify/next-runtime/assets/106944652/6e7b0c11-38ad-417b-9a03-2986709567eb](https://github.com/netlify/next-runtime/assets/106944652/6e7b0c11-38ad-417b-9a03-2986709567eb)

---

`netlify.toml`:

```toml
[build]
  command = "pnpm run build"
  publish = ".next"
 
[[plugins]]
  package = "@netlify/plugin-nextjs"
```
